### ISSUE TITLE
True dark mode?

### ISSUE THREAD

**Issue by Prasantacharya** [quacs/quacs#210]
when is true dark mode coming to quacs?

**Comment by johnnyapol** [comment]
PACS features true dark mode if you would like to try

**Comment by chrisj1** [comment]
Careful @benjaminrsherman @elihschiff will mark this as too heated if you speak the truth

**Comment by Prasantacharya** [comment]
can you give me a link to the source code?

**Comment by chrisj1** [comment]
> can you give me a link to the source code?

https://github.com/PACS-RPI

**Comment by benjaminrsherman** [comment]
True dark mode is an accessibility concern as it makes it extremely difficult to interact with the website, which is why we decided to reject it.

**Comment by chrisj1** [comment]
Fixed in #964
