### ISSUE TITLE
Semester Drop-Down Tooltips are Wrong

### ISSUE THREAD

**Issue by Shadowsoftime99** [quacs/quacs#237]
![image](https://user-images.githubusercontent.com/16748195/100801856-8e75fa80-33f6-11eb-84ca-328faa2bd1fd.png)

As you can see, the hover tooltip for every entry in this list is always the newest semester (Spring 2021) instead of what's actually being hovered on.

**Comment by Shadowsoftime99** [comment]
And it's already fixed on live; Github just didn't auto-close the issue as there was no PR. Cool!

**Comment by benjaminrsherman** [comment]
Rip I thought it would autoclose if mentioned in a commit... I guess not :(
