### ISSUE TITLE
Add building floorplans 

### ISSUE THREAD

**Issue by elihschiff** [quacs/quacs#295]
Ideally courses would be able to link to their associated building however there should also be a page to view all the floor plans. People may be interested in looking at the floor plans for specific buildings such as dorms

http://zim2411.info/floorplans/ this would need to be added to the data repo

**Comment by benjaminrsherman** [comment]
I really think that we should keep QuACS scoped to just course information.  We could spawn a spin-off site of "all RPI information", but adding that information into QuACS will just bloat the site in my opinion.

**Comment by elihschiff** [comment]
I added the data to quacs-data here https://github.com/quacs/quacs-data/tree/master/Floor%20Plans

quacs-data has always been a random data aggregation repo so I think if fits the scope of that part of QuACS better while not interfering with the main purpose of the quacs.org site
