### ISSUE TITLE
change schedule.ics to {course_set_name}.ics

### ISSUE THREAD

**Issue by elihschiff** [quacs/quacs#319]
change schedule.ics to {course_set_name}.ics

Should be really easy to do, probably one line of code

**Comment by io12** [comment]
I vote making the output snake-case to avoid outputting filenames with spaces.

Example: `quacs-course-set-1.ics`

There are probably lots of typescript case conversion libraries but here's one I found with a quick search: https://github.com/blakeembrey/change-case/tree/master/packages/param-case
