### ISSUE TITLE
Add sub-semester support (aka RPI summer arch support)

### ISSUE THREAD

**Issue by elihschiff** [quacs/quacs#324]
Ideally this should not need to be hard coded in any way, and calculates the sub-semesters automatically.
 
We need to think about how we want to add this to the scraper/conflicting bits. I am not sure the best way to do this tbh. Any thoughts would be appreciated.

For the front end I was thinking, split each sub-semester into a bootstrap column. When there is 1 semester it takes up the full screen width, when there are 2 it should go split screen assuming that the screen is large enough. On smaller screens they should stack. If there are >2 just start stalking them in 2 wide columns on large screens and 1 wide columns on small screens.
Another option is to have a button to cycle though each sub-semester. I am worried people wont notice this button and get confused though.

Once we get the scraper working, we should be able to see based off the real data if RPI uses more than 2 sub-semesters ever and how ugly it would look if that were the case.

**Comment by benjaminrsherman** [comment]
Does the scraper/conflict bits need to change?  We already know a class's dates in the client-side data and I think it'd be simpler to refactor the schedule generation code to take a specific set of sections and we can run it per subsemester.  There might be some big performance cost to this which I'm missing though - I'll think on it some more.

A benefit of it though is that we'll make @io12 happy when we make the rust code stateless.

**Comment by io12** [comment]
Making the Rust stateless will also make unit tests and benchmarks possible.

**Comment by benjaminrsherman** [comment]
> Making the Rust stateless will also make unit tests and benchmarks possible.

That's why you'll be happy.

**Comment by elihschiff** [comment]
That method would multiply our schedule generation time by the number of sub-semesters there are. Which imo is not ideal.

In theory if we were able to factor all the data into the bits it would be faster. If say the sub-semesters are set up like summer arch. A 12 week class would just duplicate its bits. A first 6 week class would have its bits followed by a bunch of 0s while a second week class would be reversed. Then I believe the optimization code would be able to look at theses bits and optimize the total number of bits used to be much fewer. My biggest worry with this method is the speed of that optimization code.

We could make the rust stateless regardless of these other changes. They are unrelated

**Comment by johnnyapol** [comment]
https://github.com/quacs/quacs/commit/d065b1b09bbe96b71a334f3841370192805d477a

**Comment by johnnyapol** [comment]
This is already implemented in the RPI quacs-rs generators. The actual calendar + course cards should be cleaned up to indicate sub-semester courses but the heavy lifting is already done and it works.

On a side note, we should probably consolidate what features are actually implemented to prevent duplicate work being done.

**Comment by benjaminrsherman** [comment]
> This is already implemented in the RPI quacs-rs generators. The actual calendar + course cards should be cleaned up to indicate sub-semester courses but the heavy lifting is already done and it works.

The scraper end is complete, but quacs-rs itself needs to be overhauled.  The algorithm currently assumes that your courses are all on the same subsemester - that's what needs to change.

**Comment by benjaminrsherman** [comment]
> The scraper end is complete, but quacs-rs itself needs to be overhauled.

Nevermind, I forgot what that PR does.  Sorry @io12, no quacs-rs refactor for you.

**Comment by johnnyapol** [comment]
Is there anything else that needs to be considered for this or should this be closed out in favor of individual issues for bugs, refactoring, etc

**Comment by benjaminrsherman** [comment]
I think this issue is finished - there probably are smaller bugs but they can be handled separately.
