### ISSUE TITLE
Course info prerequisites should also show the prerequisites graph, if possible

### ISSUE THREAD

**Issue by benjaminrsherman** [quacs/quacs#361]
Currently the prerequisites graph only shows when looking at a section's info, but not for the whole course's.  Ideally we'd be able to show the prerequisites graph for the whole course.

**Comment by io12** [comment]
Is there a place in the UI for whole-course info? Putting the graph in the same place as the course description has issues (performance with lots of graphs at once and scrolling switching to zooming the graph).

**Comment by benjaminrsherman** [comment]
The prereq graph should be added to the CourseInfo component.  As of right now, it's visible when clicking the "Missing prerequisites" tag on courses.
