### ISSUE TITLE
CRNs with no timeslots don't show in the list of CRNs below the calendar

### ISSUE THREAD

**Issue by benjaminrsherman** [quacs/quacs#391]
Example: Engineering Econ

**Comment by benjaminrsherman** [comment]
If someone has multiple sections of a course which all don't have times, do we want to choose which one to show?

**Comment by elihschiff** [comment]
I think ideally we would show the first section CRN that is not full. If all sections are all full, just show any CRN (it does not matter)

**Comment by benjaminrsherman** [comment]
I can't believe you're making me do extra work
