### ISSUE TITLE
Add Printing Options

### ISSUE THREAD

**Issue by Xystem4** [quacs/quacs#621]
As a user, when looking at my schedule in practice I'm usually walking across campus looking at a screenshot I have on my phone. However, there is no easy way to get a nice screenshot/pdf of your quacs schedule without doing manual cropping.

Either a "export as pdf" or a "show printable view" option would be a useful addition, I feel. Showing only the actual calendar itself, without the arrows for switching through generated schedules, or the course list at the bottom.

If this feature were to be implemented, one particular aspect I would find very important would be the option to (or just do it automatically) make text resize to fit in the schedule boxes without scroll bars. Currently (at least on my screen, which is 16x9 and might not be what you're testing on), there is no way to remove the scroll bars even on the normal length 2 hour classes (zooming in just makes the text get bigger, funny enough). As such, my schedule looks like this:
![image](https://user-images.githubusercontent.com/65842664/131945303-e4b72230-8c63-4ea3-9a69-45b71a71546d.png)
Which frustratingly, when taking a screenshot, forces me to either show the name of the class, or its location (the two most important pieces of information, in my opinion), but not both.

I understand that this is easier said than done when considering some ridiculously short classes which obviously have far less space to work with, but hey I don't have any classes shorter than 2 hours so they may as well not exist

**Comment by benjaminrsherman** [comment]
How is this different from #258?

**Comment by Xystem4** [comment]
@benjaminrsherman I'd say the key difference is that I am illiterate and despite looking through the issues list multiple times didn't manage to spot that. I'll close this and add the parts I believe to be new information (namely the scroll bar stuff) as a comment to that issue.

**Comment by johnnyapol** [comment]
As a related note: as a workaround for now, you can use snipping tool (or equivalent) and take a screenshot and print that. 

Unfortunately, dumping the canvas into an image has proved to be a very problematic approach (something as simple as re-sizing your window changes the output), so that easy solution is out. We'd have to create our own rendering solution for this.
