### ISSUE TITLE
Searchbar breaks when searching and navigating to a separate page

### ISSUE THREAD

**Issue by Malorn44** [quacs/quacs#7]
If I search anything in the search bar: say "CSCI" and then go to the Schedule page, for example. If I focus on the search bar and hit enter again, nothing happens. I need to update the text for it to start searching.

My guess is that Enter just doesn't do anything right now since it seems the search bar only works when it is updated.

**Comment by benjaminrsherman** [comment]
Resolved by b696c219c6efeb7ed0df0d483bb506c9ee3ebb23.
